version: '3.3'

services:
  dev-db:
    image: postgis/postgis:9.5-3.0
    ports:
    - '5432:5432'
    environment:
      POSTGRES_PASSWORD: dev-password
      POSTGRES_USER: dev-user
      POSTGRES_DB: devdb
      POSTGRES_ADMIN_PASSWORD: dev-admin-password